# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160623_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='shop/static/shop/img/'),
        ),
    ]
